// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Wed Oct 16 20:37:06 2019

IC74HC151 IC74HC151_inst
(
	.EN_Part(EN_Part_sig) ,	// input  EN_Part_sig
	.SelectPart(SelectPart_sig) ,	// input [DATA_SelectPart-1:0] SelectPart_sig
	.Single_Part(Single_Part_sig) ,	// input [DATA_Single_Part-1:0] Single_Part_sig
	.Y(Y_sig) ,	// output  Y_sig
	.YF(YF_sig) 	// output  YF_sig
);

defparam IC74HC151_inst.DATA_SelectPart = 3;
defparam IC74HC151_inst.DATA_Single_Part = 8;
